### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by fhennig** [GenSpectrum/LAPIS#991] opened 2024-10-16 08:14 UTC
Hi, I couldn't find documentation for the LAPIS API in the README. Where is it?

**Comment by corneliusroemer** [comment] 2024-10-21 13:11
You can find general docs here: https://lapis-three.vercel.app/

**Comment by corneliusroemer** [comment] 2024-10-21 13:12
Also, see #928

**Comment by Taepper** [comment] 2024-10-21 13:32
Ah, indeed https://github.com/GenSpectrum/LAPIS/issues/928 seems to be more descriptive and a duplicate of this. I will therefore close this as a duplicate. It is still on the agenda for Wednesday and we will prioritize it accordingly

**Closed by Taepper** 2024-10-21 13:32 UTC
