### ISSUE TITLE
Add healthcheck to LAPIS / docker-compose

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS#941] opened 2024-09-06 15:02 UTC
Currently, the LAPIS docker image does not have a healthcheck and also the contained [docker-compose file](https://github.com/GenSpectrum/LAPIS/blob/main/lapis/docker-compose.yml) that starts both LAPIS and SILO does not have a healthcheck defined.

A race condition when the compose file is called with `--wait` is the reason this healthcheck is required.

If silo is started in the docker compose file with port-mapping `-p 8000:8081`, the url `http://silo:8081` in LAPIS becomes available *after* `localhost:8000` is available outside the container (sometimes several seconds). This leads to race conditions, if you are dependent on the `docker compose up --wait` to only return after LAPIS is queryable. 

This can also be fixed outside the LAPIS Dockerfile as shown in https://github.com/GenSpectrum/LAPIS-SILO-e2e/pull/26

I think that adding a healthcheck in LAPIS that queries its own `localhost:8080/sample/aggregated` endpoint should have only positive effects. At the very least we should amend the [docker-compose file](https://github.com/GenSpectrum/LAPIS/blob/main/lapis/docker-compose.yml), as we are also subject to this race condition in the LAPIS CI, although it is way less likely due to `npm run test` being called after the starting of the container. If we do not implement an internal check, we should also document this, as it will be quite common for downstream consumers to start both LAPIS and SILO using docker compose.

**Comment by fengelniederhammer** [comment] 2024-09-09 06:38
Duplicate of #813

**Closed by fengelniederhammer** 2024-09-09 06:38 UTC
